README.md
And remove redundant header info
=> Update readme with Travis badge

example/route_guide/README.md, example/route_guide/lib/src/client.dart, example/route_guide/lib/src/generated/route_guide.pb.dart, example/route_guide/lib/src/generated/route_guide.pbgrpc.dart
Updated README.md with instructions on how to regenerate the code.
Fixes #11.
=> Generated code using new protoc Dart gRPC plugin.

.travis.yml, interop/bin/server.dart, interop/lib/src/generated/empty.pb.dart, interop/lib/src/generated/messages.pb.dart, interop/lib/src/generated/messages.pbenum.dart, interop/lib/src/generated/test.pb.dart, interop/lib/src/generated/test.pbgrpc.dart, interop/protos/empty.proto, interop/protos/messages.proto, interop/protos/test.proto, interop/pubspec.yaml, interop/tool/regenerate.sh, lib/grpc.dart, lib/src/server.dart
Implements the basic server interoperability tests for gRPC compliance.
Compressed tests, TLS, and authentication are not implemented yet, but
basic test cases pass against the C++ gRPC interoperability client.
Part of #10.
=> Basic server interoperability tests.

lib/src/client.dart, lib/src/server.dart, lib/src/shared.dart, test/src/client_utils.dart, test/src/server_utils.dart, test/timeout_test.dart
=> Add timeout handling.

example/metadata/lib/src/generated/metadata.pb.dart, example/route_guide/README.md, example/route_guide/lib/src/generated/route_guide.pb.dart, example/route_guide/lib/src/generated/route_guide.pbgrpc.dart, interop/lib/src/generated/messages.pb.dart, interop/lib/src/generated/test.pbgrpc.dart, lib/src/client.dart
Preparation for updating the call generation logic.
=> Update generated code using latest protoc_plugin.

.github/ISSUE_TEMPLATE, CODE-OF-CONDUCT.md, CONTRIBUTING.md
Complete the repo config to be consistent with other grpc repos
=> Repo config

CHANGELOG.md, example/googleapis/README.md, example/googleapis/lib/src/generated/google/api/label.pb.dart, example/googleapis/lib/src/generated/google/api/monitored_resource.pb.dart, example/googleapis/lib/src/generated/google/logging/type/http_request.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/log_entry.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/log_entry.pbjson.dart, example/googleapis/lib/src/generated/google/logging/v2/logging.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/logging.pbgrpc.dart, example/googleapis/lib/src/generated/google/protobuf/any.pb.dart, example/googleapis/lib/src/generated/google/protobuf/duration.pb.dart, example/googleapis/lib/src/generated/google/protobuf/struct.pb.dart, example/googleapis/lib/src/generated/google/protobuf/timestamp.pb.dart, example/googleapis/lib/src/generated/google/rpc/status.pb.dart, example/googleapis/pubspec.yaml, example/metadata/lib/src/generated/metadata.pb.dart, example/metadata/lib/src/generated/metadata.pbgrpc.dart, example/metadata/pubspec.yaml, example/route_guide/README.md, example/route_guide/lib/src/generated/route_guide.pb.dart, example/route_guide/lib/src/generated/route_guide.pbgrpc.dart, example/route_guide/pubspec.yaml, interop/lib/src/generated/messages.pb.dart, interop/lib/src/generated/test.pbgrpc.dart, interop/pubspec.yaml, lib/src/client/connection.dart, pubspec.yaml
Updated generated code in examples using latest protoc compiler plugin.
Fixed uses-dynamic-as-bottom issues.
=> Dart 2.0 fixes.

CHANGELOG.md, example/googleapis/bin/logging.dart, example/googleapis/pubspec.yaml, interop/lib/src/client.dart, lib/grpc.dart, lib/src/auth/auth.dart, lib/src/client/call.dart, lib/src/client/connection.dart, lib/src/client/options.dart, pubspec.yaml, test/client_test.dart
Added authentication provider classes, and wired up the auth interop
tests.
Refactored connection logic to throw initial connection errors early.
Fixes #53
=> Authenticated cloud-to-prod interop tests.

interop/lib/src/client.dart
=> Fix GCE auth interop test.

example/helloworld/README.md, example/helloworld/bin/client.dart, example/helloworld/bin/server.dart, example/helloworld/lib/src/generated/helloworld.pb.dart, example/helloworld/lib/src/generated/helloworld.pbenum.dart, example/helloworld/lib/src/generated/helloworld.pbgrpc.dart, example/helloworld/lib/src/generated/helloworld.pbjson.dart, example/helloworld/protos/helloworld.proto, example/helloworld/pubspec.yaml
This will be used in the quickstart docs, similar to the other
languages.
=> Add helloworld example.

example/helloworld/bin/server.dart, example/metadata/lib/src/server.dart, example/route_guide/lib/src/server.dart, interop/bin/server.dart, lib/src/server/server.dart, test/src/server_utils.dart
Add address parameter for server, to control which address to listen to,
and the ability to use an ephemeral port.
=> Move TLS credentials for server into a separate class.

pubspec.yaml
=> Widen version constraint for async.

example/googleapis/pubspec.yaml, example/helloworld/pubspec.yaml, example/metadata/pubspec.yaml, example/route_guide/lib/src/common.dart, example/route_guide/pubspec.yaml, interop/bin/server.dart, interop/pubspec.yaml, lib/src/auth/auth.dart, lib/src/client/call.dart, lib/src/server/handler.dart, lib/src/server/service.dart
Fixes runtime type errors in Dart 2 mode.
=> Dart 2 fixes

example/googleapis/lib/src/generated/google/api/monitored_resource.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/log_entry.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/logging.pb.dart, example/googleapis/lib/src/generated/google/logging/v2/logging.pbgrpc.dart, example/googleapis/lib/src/generated/google/protobuf/struct.pb.dart, example/googleapis/lib/src/generated/google/rpc/status.pb.dart, example/helloworld/lib/src/generated/helloworld.pbgrpc.dart, example/metadata/lib/src/generated/metadata.pbgrpc.dart, example/route_guide/lib/src/generated/route_guide.pbgrpc.dart, interop/lib/src/generated/messages.pb.dart, interop/lib/src/generated/test.pbgrpc.dart, test/src/client_utils.dart
Also updated generated code using latest protoc_plugin, for Dart 2 updates.
=> Fix tests in Dart 2 mode.

example/googleapis/pubspec.yaml, example/helloworld/pubspec.yaml, example/metadata/pubspec.yaml, example/route_guide/pubspec.yaml, interop/pubspec.yaml
Fixes https://github.com/grpc/grpc-dart/issues/73
=> #73 removed version from example pubspecs

.travis.yml, README.md, pubspec.yaml, test/src/client_utils.dart, test/timeout_test.dart
Also increases a timeout to make it work with sync_async
=> Update test dependencies

CHANGELOG.md, lib/src/auth/auth.dart, lib/src/client/call.dart, lib/src/server/server.dart, lib/src/shared/streams.dart, lib/src/shared/timeout.dart, pubspec.yaml, test/src/client_utils.dart
Updated using https://github.com/dart-lang/dart2_fix
=> Use new Dart 2 APIs

CHANGELOG.md, analysis_options.yaml, example/route_guide/lib/src/common.dart, example/route_guide/lib/src/server.dart, interop/bin/server.dart, lib/src/shared/timeout.dart, pubspec.yaml, test/options_test.dart, test/src/utils.dart, test/stream_test.dart
I also went ahead and fixed some other deprecated calls and removed the
no-longer-needed strong-mode flag.
=> Finish migrating to the Dart 2 core library constants.

CHANGELOG.md, lib/src/client/connection.dart, lib/src/server/handler.dart, lib/src/shared/streams.dart, pubspec.yaml
Hopefully this will fix https://github.com/grpc/grpc/issues/16004
=> Allow for non ascii headers

CHANGELOG.md, pubspec.yaml
To publish changes from **https://github.com/grpc/grpc-dart/pull/117**
=> Version bump

CHANGELOG.md, README.md, pubspec.yaml
Fixes https://github.com/grpc/grpc-dart/issues/137
=> Graduate package to 1.0 stable

lib/src/client/call.dart, lib/src/client/http2_channel.dart, lib/src/client/options.dart, lib/src/client/web_channel.dart, lib/src/shared/message.dart, lib/src/shared/streams.dart
This should make us dart 2.0 compatible again.
=> Fix imports

lib/src/client/options.dart
Fixes https://github.com/grpc/grpc-dart/issues/176.
=> Allow authority for insecure connections

lib/src/client/transport/web_streams.dart, lib/src/shared/message.dart, test/grpc_web_decoding_test.dart
This fixes https://github.com/grpc/grpc-dart/issues/168
=> Fix empty repeated

CHANGELOG.md, lib/src/client/call.dart, lib/src/client/connection.dart, lib/src/client/http2_connection.dart, lib/src/client/transport/xhr_transport.dart, pubspec.yaml
Should fix (partially): https://github.com/grpc/grpc/issues/19505
=> Provide scheme as part of audience

pubspec.yaml
This is in response to: https://github.com/grpc/grpc-dart/issues/226
=> Relax dependency on package:meta

CHANGELOG.md, lib/src/client/http2_connection.dart, pubspec.yaml
This should fix https://github.com/grpc/grpc/issues/20017
=> Fix use of authority when making a secure connection

README.md
=> Fix grpc-web import in Readme

.gitignore
(cherry picked from commit 1a9fdd25e9d96682085bc590c8afb0373b72e9d8)
=> ignore '.idea' directory

lib/src/server/handler.dart
This should fix: https://github.com/grpc/grpc/issues/21755
=> server: Cancel call when the outgoing messages are closed

README.md, example/README.md, example/helloworld/bin/client.dart, example/helloworld/bin/server.dart, example/helloworld/lib/src/generated/helloworld.pb.dart, example/helloworld/lib/src/generated/helloworld.pbenum.dart, example/helloworld/lib/src/generated/helloworld.pbgrpc.dart, example/helloworld/lib/src/generated/helloworld.pbjson.dart, example/helloworld/pubspec.yaml, example/route_guide/lib/src/client.dart, example/route_guide/lib/src/generated/route_guide.pb.dart, example/route_guide/lib/src/generated/route_guide.pbenum.dart, example/route_guide/lib/src/generated/route_guide.pbgrpc.dart, example/route_guide/lib/src/generated/route_guide.pbjson.dart, example/route_guide/lib/src/server.dart, example/route_guide/pubspec.yaml
- Fixes #259
- Fixes #158, see https://github.com/grpc/grpc-dart/issues/158#issuecomment-473578902.
- Closes #269 because it supersedes it by fixing both the Quick Start and the Tutorial examples.
cc @thisisnotapril @mit-mit @sigurdm
=> helloworld and route_guide: update to protobuf v1

CHANGELOG.md, lib/grpc.dart, lib/src/auth/auth_io.dart, pubspec.yaml
Motivated by https://github.com/dart-lang/appengine/issues/135
=> Added Application Default Credentials Support

lib/src/client/call.dart, test/client_tests/client_test.dart
https://github.com/grpc/grpc-dart/issues/325
=> Fix decode gRPC error message

lib/src/server/handler.dart, test/server_test.dart
https://github.com/grpc/grpc-dart/issues/329
=> Encode server error message

README.md
Contributes to https://github.com/grpc/grpc.io/issues/180
cc @sigurdm @mit-mit @ejona86
=> README rework: link into language/dart page on grpc.io etc

CHANGELOG.md, pubspec.yaml
Closes #321
cc @sigurdm @mit-mit @ejona86
=> Relax crypto version constraint (for Flutter)

lib/src/client/transport/xhr_transport.dart, test/client_tests/client_xhr_transport_test.dart
This reverts commit c513e1467f21e498385f4aefa7e370601263034e.
The original commit has broken streaming due to limitations of package:http.
=> Revert "Support grpc-web in pure dart (#287)"

CHANGELOG.md, lib/src/client/call.dart, lib/src/client/transport/transport.dart, lib/src/client/transport/xhr_transport.dart, pubspec.yaml, test/client_tests/client_test.dart, test/client_tests/client_xhr_transport_test.dart, test/src/client_utils.dart
This PR syncs over some improvements to exception plumbing we did internally.
=> Beef up exception handling in gRPC code.

lib/src/client/http2_connection.dart, test/client_tests/client_test.dart
This reverts commit 9ed03b6b969b9171d5b218e0ac308ae127c56984.
This change prevents client from gracefully handling connection issues and instead just makes it infinitely trying to reconnect (#339).
=> Revert "Not to fail pending requests, just reschedule it (#303)"

.github/workflows/dart.yml
Make sure we keep working as we roll new dev releases
=> Add weekly cron to GitHub workflow

lib/src/client/transport/xhr_transport.dart, test/grpc_web_test.dart
=> Prevent an exception to be thrown when a web connection stream is closed

lib/src/client/transport/xhr_transport.dart, lib/src/shared/status.dart, test/client_tests/client_xhr_transport_test.dart
Add XHR raw response to the GrpcError for a better debugging.
=> Add XHR raw response to the GrpcError for a better debugging

lib/src/client/http2_connection.dart
Sorry for the past PR which didn't completely fix the NPE in this code.
https://stackoverflow.com/a/51141153/2531686
=> Proper NPE fix

.github/workflows/dart.yml, CHANGELOG.md, interop/lib/src/client.dart, pubspec.yaml
Also:
* updated SDK constraint to stable
* Use latest Dart action install
* Test on oldest supported SDK
=> Avoid completing multiple times for one error

CHANGELOG.md, lib/src/server/call.dart, lib/src/server/handler.dart, lib/src/server/server.dart, lib/src/shared/io_bits/io_bits_io.dart, lib/src/shared/io_bits/io_bits_web.dart, test/src/server_utils.dart
I probably should have opened an issue first, but I wanted to be able to log the client IP address in an `Interceptor`. Unless I missed this already being available somewhere, here's my solution. Thoughts?
=> Expose client IP address to server

lib/src/client/call.dart
This change was already inappropriately landed in google3.
=> Check for closed StreamController in more places

.github/workflows/dart.yml, CHANGELOG.md, lib/src/client/call.dart, lib/src/client/channel.dart, lib/src/client/common.dart, lib/src/client/transport/web_streams.dart, lib/src/shared/message.dart, lib/src/shared/profiler.dart, lib/src/shared/streams.dart, pubspec.yaml, test/timeline_test.dart, tool/test_all.sh
=> Switch to Dart 3

CHANGELOG.md, lib/src/shared/status.dart, pubspec.yaml
=> Make constructors of `GrpcError` const

analysis_options.yaml, example/grpc-web/lib/app.dart, lib/grpc.dart, lib/src/auth/auth_io.dart, lib/src/client/client_keepalive.dart, lib/src/client/client_transport_connector.dart, lib/src/client/http2_connection.dart, lib/src/client/interceptor.dart, lib/src/client/proxy.dart, lib/src/server/interceptor.dart, lib/src/server/server_keepalive.dart, test/proxy_secure_test.dart, test/proxy_test.dart, test/src/client_utils.dart, test/tools/http2_client.dart
Fix imports and export `Proxy`.
=> Fix imports in `http2_connection.dart`

.github/workflows/health.yaml, .github/workflows/post_summaries.yaml
Add a workflow to show PR health, such as missing changelog entries. See also https://github.com/dart-lang/ecosystem/tree/main/pkgs/firehose#health.
=> Add Health workflow
