example/route_guide/pubspec.yaml
pubspec.yaml

Picks up fix for sending endStream bit on the requested frame, instead
of on an empty data frame following it.
Needed for interoperability with the Go gRPC client, since it otherwise
failed to recognize the trailer frame sent from the server.
Fixes #13.

Upgrade package:http2 dependency.

---

example/metadata/README.md
example/metadata/bin/client.dart
example/metadata/bin/server.dart
example/metadata/lib/src/client.dart
example/metadata/lib/src/generated/metadata.pb.dart
example/metadata/lib/src/generated/metadata.pbgrpc.dart
example/metadata/lib/src/server.dart
example/metadata/protos/metadata.proto
example/metadata/pubspec.yaml
example/metadata/tool/regenerate.sh
example/route_guide/README.md
example/route_guide/lib/src/client.dart
lib/src/client.dart
lib/src/server.dart
test/timeout_test.dart

Added an example showing how to send/receive custom metadata, and handle
call cancellation.
Implemented the remaining parts of metadata and cancel handling.
Addresses part of #8 and #12.

Custom metadata and call cancellation.

---

.travis.yml

Using `dart_task: dartanalyzer lib test` didn't actually work - looks like Travis just runs the tests instead of the analyzer.
So let's try a custom script instead.

Fix analyze task

---

example/metadata/lib/src/client.dart
example/metadata/lib/src/generated/metadata.pb.dart
example/metadata/lib/src/generated/metadata.pbgrpc.dart
example/route_guide/lib/src/client.dart
example/route_guide/lib/src/generated/route_guide.pbgrpc.dart
interop/bin/server.dart
interop/lib/src/generated/empty.pb.dart
interop/lib/src/generated/messages.pb.dart
interop/lib/src/generated/messages.pbenum.dart
interop/lib/src/generated/test.pb.dart
interop/lib/src/generated/test.pbgrpc.dart
lib/src/client.dart
lib/src/server.dart
test/client_test.dart
test/src/client_utils.dart
test/src/server_utils.dart
test/src/utils.dart
test/timeout_test.dart

First stage of separating Connection from Channel. A Channel manages
multiple Connections, and chooses which Connection to send an RPC on.
In this change, the Channel still creates a Connection for each RPC.
Managing the Connection life-cycle comes in a later change.

Preparation for RPC multiplexing

---

example/route_guide/lib/src/client.dart
lib/src/client.dart
lib/src/server.dart
lib/src/shared.dart
lib/src/streams.dart
test/client_test.dart
test/options_test.dart
test/src/client_utils.dart

A Channel will now multiplex RPCs on a single managed connection. The
connection will attempt to reconnect on failure, and will close the
underlying transport connection if no RPCs have been made for a while.
Part of #5.

Multiplex RPCs on a single connection.

---

test/src/client_utils.dart

Mockito will soon start throwing an ArgumentError if thenReturn()
is called with a Future or Stream, as this can result in difficult
to trace errors.

Use thenAnswer() instead of thenReturn() when returning a Stream.

---

test/src/server_utils.dart

This override was just missing a variable name, hence the type was misinterpreted as the variable name.

Fix bad override in test.

---

example/googleapis/bin/logging.dart
example/helloworld/bin/client.dart
example/metadata/lib/src/client.dart
example/route_guide/lib/src/client.dart
example/route_guide/lib/src/server.dart
interop/lib/src/client.dart
lib/src/client/call.dart
lib/src/client/channel.dart
lib/src/client/connection.dart
lib/src/client/options.dart
lib/src/server/server.dart
test/options_test.dart
test/src/client_utils.dart

Add a 'bad certificate handler' to the new ChannelCredentials, which can
be used to override certificate validation (for example, to allow
auto-generated self-signed certificates during development).
Also fixed a bug in Server.shutdown().

Split out TLS credentials to a separate class.

---

lib/src/client/connection.dart

Even if _transport.finish()/terminate() returns some other kind of
Future.

Ensure shutdown and terminate always return a Future<Null>.

---

CHANGELOG.md
lib/src/shared/status.dart
pubspec.yaml

This enables using the codes in switch statements and default values.
Fixes https://github.com/grpc/grpc-dart/issues/102

Make Status codes `static const` instead of `static final`.

---

CHANGELOG.md
lib/src/client/channel.dart
pubspec.yaml

If channel is not open calling `terminate()` or `shutdown` triggered Error:
```
Unhandled exception:
NoSuchMethodError: The method 'shutdown' was called on null.
Receiver: null
Tried calling: shutdown()
#0      Object.noSuchMethod (dart:core/runtime/libobject_patch.dart:46:5)
#1      ClientChannel.shutdown (package:grpc/src/client/channel.dart:50:24)
```

don't throw on closing channel not open

---

example/googleapis/bin/logging.dart
example/helloworld/bin/client.dart
example/helloworld/bin/server.dart
example/metadata/lib/src/client.dart
example/metadata/lib/src/server.dart
example/route_guide/lib/src/client.dart
example/route_guide/lib/src/server.dart
interop/bin/server.dart
interop/lib/src/client.dart
lib/src/auth/auth.dart
lib/src/client/call.dart
lib/src/client/common.dart
lib/src/client/connection.dart
lib/src/client/options.dart
lib/src/server/server.dart
test/client_test.dart
test/src/client_utils.dart

Replace usage of `Future<Null>` with `Future<void>`.
This is a large-ish but trivial change. Using `Future<void>` is preferred to `Future<Null>`.
In addition, the `FutureOr<Null>` typedef for MetadataProviders actually breaks when defining a function that returns `void`. Since `FutureOr<T>` functions can return `Future<T>` or `T`, a provider that doesn't return a future would have to explicitly return `null`. This change should allow metadata provider functions to return `void` and `Future<void>`.

Sync internal repo changes.

---

example/grpc-web/web/main.dart
interop/lib/src/client.dart
lib/grpc.dart
lib/grpc_web.dart
lib/src/client/call.dart
lib/src/client/channel.dart
lib/src/client/connection.dart
lib/src/client/http2_channel.dart
lib/src/client/method.dart
lib/src/client/options.dart
lib/src/client/transport/http2_credentials.dart
lib/src/client/transport/http2_transport.dart
lib/src/client/transport/transport.dart
lib/src/client/transport/xhr_transport.dart
lib/src/client/web_channel.dart
test/client_tests/client_http2_transport_test.dart
test/client_tests/client_xhr_transport_test.dart
test/options_test.dart
test/src/client_utils.dart

`ChannelCredentials` is now a http2-only-thing
`ClientCall` now asks the `Transport` about the authority.
The Xhr client-channel now takes a Uri.

Improve interfaces

---

lib/grpc.dart
lib/grpc_web.dart
lib/service_api.dart
lib/src/auth/auth.dart
lib/src/client/call.dart
lib/src/client/client.dart
lib/src/client/connection.dart
lib/src/client/http2_channel.dart
lib/src/client/http2_connection.dart
lib/src/client/options.dart
lib/src/client/transport/http2_credentials.dart
lib/src/client/transport/xhr_transport.dart
lib/src/client/web_channel.dart

The ChannelOptions we have do not make sense for grpc-web. They are now http2-only.

Export less from grpc-web.dart

---

test/timeout_test.dart

The 2ms seem to not be enough on travis.

Wait longer for timeout in timeout_test

---

CHANGELOG.md
lib/src/client/http2_connection.dart
pubspec.yaml
test/client_tests/client_test.dart

The expression was totally broken.
Should fix (part-of) interop tests https://github.com/grpc/grpc/issues/16580
Side-note: the lack of complaints about this probably means we have no active users of jwt auhtorization.

Fix interop

---

interop/bin/server.dart
interop/lib/src/client.dart

This was implemented by accident in https://github.com/grpc/grpc-dart/commit/6c0f61aaf671e601f6833072705dc7ae8aab7751 .
Should fix https://github.com/grpc/grpc/issues/16580

Unimplement unimplementedMethod in interop

---

CHANGELOG.md
lib/src/client/http2_connection.dart
lib/src/server/server.dart
lib/src/shared/message.dart
lib/src/shared/status.dart
pubspec.yaml

Fixes: https://github.com/grpc/grpc-dart/issues/196
1) Let GrpcError implement exception
As the user is (usually) expected to catch these they should implement
Exception.
There is a bigger clean-up in splitting off the GrpcError.internal as
that seems to be for invariant violations
2) Convert some thrown strings into exceptions.

Improve error handling

---

CHANGELOG.md
lib/src/client/http2_connection.dart
pubspec.yaml

Should fix https://github.com/grpc/grpc-dart/issues/219 and https://github.com/grpc/grpc-dart/issues/237

Use host without port as authority when making secure connection

---

lib/grpc_connection_interface.dart

To create an alternate implementation of `ClientChannel`, we currently need to import symbols from `lib/src` which are "[private](https://dart.dev/tools/pub/package-layout#implementation-files)" to the package. This change exports them as part of the public API.
Internal bug: b/152361560

Export more symbols for alternate implementation of `ClientChannel`

---

lib/src/client/http2_connection.dart
lib/src/server/server.dart

This supersedes/replicates https://github.com/grpc/grpc-dart/pull/275.
Fixes https://github.com/grpc/grpc-dart/issues/249

Use tcpNoDelay option for sockets

---

lib/src/client/http2_connection.dart
test/client_tests/client_test.dart

Pending calls never started, it doesn't make sense fail it, when connection established all calls will be rescheduled. See https://github.com/grpc/grpc-dart/blob/master/lib/src/client/http2_connection.dart#L129

Not to fail pending requests, just reschedule it

---

lib/src/client/http2_connection.dart

We beefed up security on iOS and Android embeddings of Flutter. We no longer allow `Socket.connect` since it is insecure. `gRPC` was doing unnecessary `connect -> secure` step. This is not needed if authority is not supplied and the library is supposed to use the same authority host as the destination host.
See relevant bug in SDK: https://github.com/dart-lang/sdk/issues/43223

Use SecureSocket.connect directly if there's no authority in Credentials

---

example/route_guide/lib/src/client.dart

The `channel` variable should be a local variable rather than a member of `Client`. (This is in part a followup to #286 and https://github.com/grpc/grpc.io/issues/386.)
@sigurdm @mit-mit 
I've manually tested the route guide example to ensure that it still works as intended.
Related: https://github.com/grpc/grpc.io/pull/395

Example: route guide client cleanup

---

.travis.yml

Updated package (with correct checksum) is stuck in moderation which causes installation errors because installer itself has been already updated.

Fix for Windows Travis builds

---

CHANGELOG.md
lib/grpc.dart
lib/service_api.dart
lib/src/server/server.dart
pubspec.yaml

Sync from internal that gives some more client validation ability to server credentials.
Also, expose `MetadataProvider` in the service API to provide utility functions in various Flutter libraries.

Add client validation to server credentials

---

CHANGELOG.md
lib/grpc.dart
lib/src/client/client_transport_connector.dart
lib/src/client/http2_channel.dart
lib/src/client/http2_connection.dart
lib/src/server/server.dart
pubspec.yaml
test/client_tests/client_transport_connector_test.dart
test/connection_server_test.dart
test/src/client_utils.dart
test/src/server_utils.dart

This allows callers to propvide their own transport configuration, such
as their own implementation of streams and sinks instead of sockets.
* Extract ConnectionServer from Server to support ServerTransportConnection
* Add ClientTransportConfig to support ClientTransportConnection
* Plumb ClientTransportConfig from Channel to Http2ClientConnection

Create gRPC servers and clients with TransportConnections.

---

.travis.yml

Reverts grpc/grpc-dart#359
We no longer need this workaround (also it is breaking the builds now)

Revert "Fix for Windows Travis builds"

---

lib/src/auth/auth_io.dart
lib/src/client/client.dart
lib/src/client/connection.dart

Since Dart 2.1, Future and Stream have been exported from dart:core

Remove unused dart:async imports

---

.travis.yml
CONTRIBUTING.md
pubspec.yaml
test/grpc_web_server.dart
test/grpc_web_test.dart
test/src/generated/echo.pb.dart
test/src/generated/echo.pbenum.dart
test/src/generated/echo.pbgrpc.dart
test/src/generated/echo.pbjson.dart
test/src/protos/echo.proto
tool/install-grpcwebproxy.sh

We did not have any before which allowed for regressions like #306 to
slip through. Unfortunately we can't test gRPC-web implementation
in pure Dart because we don't have a server side implementation of
the protocol. Instead we add a dependency on the third party
gRPC-web proxy (grpcwebproxy by Improbable Engineering - the choice made
purely based on the simplicity of installation) which forwards all
request gRPC server (written in Dart).

Add a simple end-to-end gRPC-web test

---

lib/src/server/handler.dart
test/round_trip_test.dart

This PR solves the issue https://github.com/grpc/grpc-dart/issues/341, where the server will crash when an exception is thrown from the onMetadata method.
It handles the exception in order for the exception to be returned to the client, the request not being processed, yet the server not crashing.
Fixes https://github.com/grpc/grpc-dart/issues/341

Call to onMetadata handles exceptions

---

CHANGELOG.md
example/helloworld/bin/client.dart
example/helloworld/bin/server.dart
lib/grpc.dart
lib/src/client/call.dart
lib/src/client/http2_connection.dart
lib/src/client/options.dart
lib/src/client/transport/http2_transport.dart
lib/src/server/handler.dart
lib/src/server/server.dart
lib/src/shared/codec.dart
lib/src/shared/codec_registry.dart
lib/src/shared/message.dart
lib/src/shared/streams.dart
pubspec.yaml
test/client_tests/client_test.dart
test/round_trip_test.dart
test/shared_tests/codec_registry_test.dart
test/src/client_utils.dart
test/src/server_utils.dart
test/src/utils.dart

1. Add method level and server level compression and decompression.
2. Client can specify a comma separated encodings such as `gzip,identity` which is passed along in `grpc-accept-encoding` header.
3. server picks the first valid option from encodings that it can support and adds `grpc-encoding` in the response headers. 
4. Client decompresses the response body using the `grpc-encoding` in the header.

Support message compression

---

lib/src/client/call.dart
test/grpc_web_server.dart

c48af638a54225fe39200df726440ac7bde4225c accidentally introduced a dependency on VM specific libraries in the shared code (apparently not caught by the tests?). `webdev` however refuses to build `grpc_web.dart` after it.

Make sure that grpc_web.dart builds on the Web

---

example/grpc-web/pubspec.yaml
interop/bin/client.dart
interop/bin/server.dart
interop/lib/src/client.dart
interop/lib/src/generated/empty.pb.dart
interop/lib/src/generated/messages.pb.dart
interop/lib/src/generated/messages.pbenum.dart
interop/lib/src/generated/test.pb.dart
interop/lib/src/generated/test.pbgrpc.dart
interop/pubspec.yaml
pubspec.yaml

Also replace dependency_overrides with published versions
interop generated sources were regenerated using yet unmerged version of protoc_plugin (see https://github.com/dart-lang/protobuf/pull/466)
After this change I could run gRPC interop tests locally

Update interop to null-safe grpc-dart

---

example/grpc-web/pubspec.yaml
pubspec.yaml

Also updated homepage -> repository
Towards https://github.com/grpc/grpc-dart/issues/367

Move to published, null-safey packages

---

lib/src/server/call.dart
lib/src/server/handler.dart
lib/src/server/server.dart
test/client_certificate_test.dart

The current server implementation does not allow to access the certificate of the client in an incoming call. The main reason for accessing the client certificate in a call is to authenticate the underlying user. To this purpose we extended the ServiceCall with a new getter `X509Certificate? get clientCertificate;`. The client certificate is then obtained from the SecureSocket and passed through. To request/require the client certificate, the `Server.serve()` method has two new optional parameters `requestClientCertificate` and `requireClientCertificate`, which are used in `SecureServerSocket.bind()` to make the certificate request.

Make clientCertificate available in ServiceCall

---

lib/grpc_or_grpcweb.dart
lib/src/client/grpc_or_grpcweb_channel_grpc.dart
lib/src/client/grpc_or_grpcweb_channel_web.dart
test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
test/client_tests/grpc_or_grpcweb_channel_web_test.dart

Using the same port is a standard for AspNetCore gRPC server.
@mraleph
@gustav3d

GrpcOrGrpcWeb: remove checking if ports are different (#482)

---

lib/grpc_or_grpcweb.dart
lib/src/client/grpc_or_grpcweb_channel_grpc.dart
lib/src/client/grpc_or_grpcweb_channel_web.dart
test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
test/client_tests/grpc_or_grpcweb_channel_web_test.dart

@mraleph 
btw: it would be soooo awesome if https://github.com/dart-lang/language/issues/723 was implemented, so that it would be transparent for library users if they are using a 'native' constructor or an extension  ;-)
(for example [here](https://github.com/morgwai/grpc-dart/blob/grpcOrWebConstructors/test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart#L26) I could write
```dart
GrpcOrGrpcWebClientChannel.toSingleEndpoint(...);
```
instead of 
```dart
GrpcOrGrpcWebClientChannelConstructors.toSingleEndpoint(...);
```
)

GrpcOrGrpcWeb: provide more flexible constructors (#484)

---

lib/src/client/client.dart
test/client_tests/client_interceptor_test.dart

The operations on the request stream of the ClientInerceptor items are ignored when calls the last invoker which creates the ResponseStream.

Fix a typo on the inner invoker parameters

---

test/client_certificate_test.dart

Use of client's context for the server results in the server not able to correctly handle ALPN selection: server is not able to request http2(the only one that grpc-dart supports) when client offers both http1 and http2, results in client attempting http1 failing to establish the connection.

Ensure server's security context is used for the server.

---

CHANGELOG.md
lib/src/client/channel.dart
lib/src/client/connection.dart
lib/src/client/http2_channel.dart
lib/src/client/http2_connection.dart
lib/src/client/transport/xhr_transport.dart
lib/src/client/web_channel.dart
pubspec.yaml
test/client_handles_bad_connections_test.dart
test/client_tests/client_test.dart
test/client_tests/client_transport_connector_test.dart
test/round_trip_test.dart
test/timeline_test.dart

This offers a Stream<ConnectionState> on channels. Only for Http2Channel, not for web usage.
Usage:
clientChannel.onConnectionStateChanged.listen(...)
This is an alternative to #563. Only merge one of these.

Expose onConnectionStateChanged for channels

---

lib/src/server/handler.dart
test/round_trip_test.dart

A previous PR #493 solved the problem of receiving trailers within the GrpcError object from the client. It works well with servers built in other languages that send those trailers. But the piece that was still missing is the inclusion of those trailers when this library is being used on the server.
So, if the following method on the server throws an error containing trailers:
```dart
throw GrpcError.custom(
StatusCode.internal,
'This error should contain trailers',
null,
null,
{
'key1': 'value1',
'key2': 'value2',
},
);
```
The client should be receiving the trailers, just like it would from a server developed on any other gRPC server language. The following client-side code should print ```It has the trailers: {key1: value1, key2: value2}```.
```dart
Future<void> main(List<String> …
```

Send trailers included on GrpcError object

---

CHANGELOG.md
lib/src/client/http2_connection.dart
test/common.dart
test/round_trip_test.dart

We were using path to the UDS socket itself, which is incorrect authority value and was tripping checks in some HTTP2 protocol implementations.
Instead default authority to localhost, which seems like a sensible value.
Fixes https://github.com/grpc/grpc-dart/issues/576

Change default authority for UDS connections.

---

CHANGELOG.md
example/helloworld/bin/server.dart
example/helloworld/bin/unix_server.dart
example/metadata/lib/src/server.dart
example/route_guide/lib/src/server.dart
interop/bin/server.dart
lib/src/server/handler.dart
lib/src/server/server.dart
test/client_certificate_test.dart
test/client_handles_bad_connections_test.dart
test/grpc_web_server.dart
test/round_trip_test.dart
test/server_handles_broken_connection_test.dart
test/src/server_utils.dart
test/timeline_test.dart

This picks up where #520 left off and resolves #51.
My particular use case is needing to log (with stack traces) gRPC errors as they occur on the server, such as those having to do with deserialization.
cc: @mraleph

Custom Error Handling for Server

---

lib/src/client/http2_connection.dart

Reverts grpc/grpc-dart#522
The commit was causing interop tests to fail.

Revert "Remove or skip callbacks on old connections"

---

lib/src/client/common.dart

The `StreamView` class from the SDK provides all the worthwhile behavior of `DelegatingStream` and the latter may soon be deprecated.

Extend StreamView over DelegatingStream

---

CHANGELOG.md
lib/grpc_connection_interface.dart
lib/src/client/channel.dart
lib/src/client/http2_channel.dart
lib/src/client/web_channel.dart
pubspec.yaml

Add a way to react to the channel shutdown or termination with an optional callback.
This is not necessarily the API which I would recommend, but this is the API that was already inappropriately shipped and in use internally.

Add a ChannelShutdownHandler callback

---

CHANGELOG.md
lib/grpc.dart

This change was made internally without documentation or review discussion during a sync from github.

Export the Code protobuf

---

CHANGELOG.md
lib/grpc.dart
lib/src/client/client_keepalive.dart
lib/src/server/server.dart
lib/src/server/server_keepalive.dart
pubspec.yaml
test/keepalive_test.dart
test/src/client_utils.dart

- Fix interop tests by not canceling all handlers when a connection is done, but just the handlers of that connection.
- Some small cleanups of keepalive.

Fix interop tests

---

CHANGELOG.md
lib/src/server/handler.dart
lib/src/server/server.dart
test/server_cancellation_test.dart

To avoid filling up the list with canceled streams.

Remove canceled streams

---

example/README.md

Corrected typo "RPs" to "RPCs". To avoid confusion.
RPC stand for Remote Procedure Call.

Typo Correction in README.md

---

.github/workflows/dart.yml
lib/grpc.dart
lib/src/shared/status.dart

To make replacing imports easier on importing into google3.
Disable test for now, see https://github.com/grpc/grpc-dart/issues/697

Make protobuf generated imports absolute

---

.github/workflows/dart.yml
CHANGELOG.md
lib/src/shared/message.dart
pubspec.yaml
test/grpc_compression_flag_test.dart

https://grpc.github.io/grpc/core/md_doc_compression.html indicates that compression flag should not be set if grpc-encoding is identity.
This PR makes grpc-dart set the compression flag properly in this case.

Fix issue 669

---

CHANGELOG.md
lib/src/client/transport/web_streams.dart

When hot-restarting in Flutter Web, streaming GRPC calls can get stuck in this [method](https://github.com/grpc/grpc-dart/blob/dee1b2b43b5059ac625cf915ac062dc13ab0f274/lib/src/client/transport/web_streams.dart#L132) of `_GrpcWebConversionSink`:
```
@override
void add(ByteBuffer chunk) {
_chunkOffset = 0;
final chunkData = chunk.asUint8List();
while (_chunkOffset < chunk.lengthInBytes) {
switch (_state) {
case _GrpcWebParseState.init:
_frameType = _parseFrameType(chunkData);
break;
case _GrpcWebParseState.length:
_parseLength(chunkData);
break;
case _GrpcWebParseState.message:
_parseMessage(chunkData);
break;
}
}
_chunkOffset = 0;
}
```
The `while` loop runs, but the `switch` statement doesn't match any cases so it just keeps looping. This seems to have something to with some issues around …

Fix hang that occurs when streaming calls are ongoing and a hot-restart occurs in Flutter web

---

CHANGELOG.md
lib/src/client/call.dart
pubspec.yaml
test/client_tests/call_test.dart
test/keepalive_test.dart

This PR attempt to solve the issue with headers not being correctly completed after a call is closed as pointed out in https://github.com/grpc/grpc-dart/issues/727
To fix the issue I have added in the `_terminate()` method a check to complete with errors any completer still going (I found `_headers` and `_trailers`)

fix: fix headers not completing when call is terminated

---

CHANGELOG.md
lib/src/client/call.dart
lib/src/shared/status.dart
pubspec.yaml

`Map.of` creates a new map with the same keys, values and *type* as the original map,
when used without type arguments or context type, where `Map.from` creates a `Map<dynamic, dynamic>`.
(This code failed on an attempt to make `Map.unmodifiable` be more strictly typed,
like `Map.of` instead of `Map.from`, showing that an intermediate map had type
`Map<dynamic, dynamic>` unnecessarily).
Same for using `List.of` instead of `List.from`.
The new code should be (microscopically) more efficient and type safe, and is forwards-compatible
with a stronger type on `Map.unmodifiable`.
(The code can be optimized more. For example
`List.of(list1)..addAll(list2)` can be just `list1 + list2` or `[...list1, ...list2]`,
both of which may know the total number of elements when doing the
initial list …

Use `Map.of` instead of `Map.from` in grpc client.

---

.github/workflows/dart.yml
CHANGELOG.md
README.md
lib/src/client/http2_connection.dart
lib/src/shared/status.dart
pubspec.yaml
test/client_tests/client_xhr_transport_test.dart
test/client_tests/grpc_or_grpcweb_channel_grpc_test.dart
test/client_tests/grpc_or_grpcweb_channel_web_test.dart
test/keepalive_test.dart
test/proxy_secure_test.dart
test/proxy_test.dart
test/server_cancellation_test.dart
test/tools/http2_client.dart

I also looked into the leaking API symbols: 
- `ServerHandler` is only visible for testing (the next version of the tool will detect this and not complain anymore)
- 'Any' as well now.
- `Duration` is used in an error constructor, we don't even want to expose that I believe.
So all good.

Small fixes

---

.github/workflows/dart.yml
CHANGELOG.md
analysis_options.yaml
lib/service_api.dart
pubspec.yaml

Ignore the `unintended_html_in_doc_comment` lint, as the lint fires on generated code from imported protobufs.
Supersedes #739.

Rev package:lints

---

CONTRIBUTING.md
README.md
analysis_options.yaml
example/grpc-web/lib/app.dart
example/grpc-web/web/main.dart
lib/grpc.dart
lib/src/client/call.dart
lib/src/client/http2_connection.dart
lib/src/client/transport/xhr_transport.dart
lib/src/server/handler.dart
lib/src/shared/io_bits/io_bits_web.dart
pubspec.yaml
test/client_tests/client_xhr_transport_test.dart
test/server_handles_broken_connection_test.dart
test/timeline_test.dart

- various analysis updates (fix several items found with `strict_top_level_inference`)
- fix indents for the `topics` and `false_secrets` sections of the pubspec file
@mosuem

various analysis updates

---

CHANGELOG.md
lib/grpc_or_grpcweb.dart
lib/src/client/transport/xhr_transport.dart
pubspec.yaml
test/client_tests/client_xhr_transport_test.dart

Fixes #715.
This includes a rebase of @minoic's https://github.com/grpc/grpc-dart/pull/730 onto the latest master, along with a couple updates.
It also updates client_xhr_transport_test to avoid dart:html, performing some ceremony to work around the unavailability of the previous mock strategy.

Fix: Migrate off legacy JS/HTML APIs

---

CHANGELOG.md
lib/src/shared/io_bits/io_bits.dart
lib/src/shared/io_bits/io_bits_web.dart

Removes HttpStatus from io_bits, thereby breaking the dependency on dart:html.
Code that previously used HttpStatus from dart:html or dart:io now gets it from package:web.
Alternatively, this could instead use HttpStatus from dart:io on platforms with dart:io and get it from package:web only otherwise. If that's preferred we can do it that way.

fix: Use package:web to get HttpStatus

---

test/grpc_web_server.dart

fix: update grpc_web_server.dart envoy config to support newer envoy

---

CHANGELOG.md
pubspec.yaml

Closes https://github.com/grpc/grpc-dart/pull/772

Allow the latest pkg:googleapis_auth

---

CHANGELOG.md
lib/grpc.dart
lib/src/server/handler.dart
lib/src/server/interceptor.dart
lib/src/server/server.dart
lib/src/server/service.dart
pubspec.yaml
test/server_test.dart
test/src/server_utils.dart

Fix for #591
Example of usage: 
```dart
class SentryInstrumenterInterceptor extends $grpc.ServerInterceptor {
@override
Stream<R> interceptStreaming<Q, R>(
$grpc.ServiceCall call,
$grpc.ServiceMethod<Q, R> method,
Stream<Q> requests,
$grpc.ServerStreamingInvoker<Q, R> invoker) async* {
final name = method.name;
final transaction = Sentry.startTransaction(method.name, 'grpc');
print('Before $name');
yield* super.interceptStreaming(call, method, requests, invoker);
print('After $name');
transaction.finish();
}
}
```
--- 
I did not check if this PR solves #611, anyway if it does not it would probably be nice to open a second PR, this one is complex enough

Add server interceptor acting as a middleware

---

CHANGELOG.md
lib/src/client/call.dart
test/client_tests/call_test.dart

It should have symmetric behavior: given `WebCallOptions a` and `CallOptions b` both `a.mergeWith(b)` and `b.mergeFrom(a)` should return `WebCallOptions`.

Fix CallOptions.mergeWith
